species: zebrafish
skeleton_index_base: 0
keypoints:
  [mouth, right_eye, left_eye, back, maw, right_tail1, left_tail1, right_tail2, left_tail2, tail3]
skeleton:
  [[0, 1], [0, 2], [0, 3], [0, 4], [3, 5], [3, 6], [5, 7], [6, 8], [7, 9], [8, 9]]
body_axis: [0, 9]
